# Generated by Django 5.0 on 2025-11-16 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicecategory',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='technician',
            name='is_available',
        ),
        migrations.AddField(
            model_name='booking',
            name='review',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, upload_to='service_images'),
        ),
        migrations.AddField(
            model_name='technician',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='technician',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
