# Generated by Django 5.0 on 2025-11-23 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
